from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton,QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui(QMainWindow):
    def __init__(self):
        super(Ui, self).__init__()
        self.init_ui()
        pass

    def init_ui(self):
        # self.setObjectName("MainWindow")
        # self.resize(793, 586)
        # self.centralwidget = QtWidgets.QWidget(self)
        # self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 60, 621, 34))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        #Top_lineEdit
        self.Top_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Top_lineEdit.sizePolicy().hasHeightForWidth())
        self.Top_lineEdit.setSizePolicy(sizePolicy)
        self.Top_lineEdit.setObjectName("Top_lineEdit")
        self.horizontalLayout.addWidget(self.Top_lineEdit)

        #Top_label
        self.Top_label = QtWidgets.QLabel(self.centralwidget)
        self.Top_label.setGeometry(QtCore.QRect(33, 21, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Top_label.setFont(font)
        self.Top_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Top_label.setObjectName("Top_label")

        #Top_pushButton
        self.Top_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Top_pushButton.setGeometry(QtCore.QRect(660, 60, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Top_pushButton.sizePolicy().hasHeightForWidth())
        self.Top_pushButton.setSizePolicy(sizePolicy)
        self.Top_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Top_pushButton.setFont(font)
        self.Top_pushButton.setObjectName("Top_pushButton")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 130, 621, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Mid_lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mid_lineEdit.sizePolicy().hasHeightForWidth())
        self.Mid_lineEdit.setSizePolicy(sizePolicy)
        self.Mid_lineEdit.setObjectName("Mid_lineEdit")
        self.horizontalLayout_2.addWidget(self.Mid_lineEdit)
        self.Mid_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.Mid_comboBox.setObjectName("Mid_comboBox")
        self.horizontalLayout_2.addWidget(self.Mid_comboBox)
        self.Mid_lable = QtWidgets.QLabel(self.centralwidget)
        self.Mid_lable.setGeometry(QtCore.QRect(30, 100, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Mid_lable.setFont(font)
        self.Mid_lable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Mid_lable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Mid_lable.setObjectName("Mid_lable")
        self.Mid_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Mid_pushButton.setGeometry(QtCore.QRect(660, 130, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Mid_pushButton.sizePolicy().hasHeightForWidth())
        self.Mid_pushButton.setSizePolicy(sizePolicy)
        self.Mid_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Mid_pushButton.setFont(font)
        self.Mid_pushButton.setObjectName("Mid_pushButton")
        self.Low_label = QtWidgets.QLabel(self.centralwidget)
        self.Low_label.setGeometry(QtCore.QRect(30, 180, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Low_label.setFont(font)
        self.Low_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Low_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Low_label.setObjectName("Low_label")
        self.Low_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.Low_textEdit.setGeometry(QtCore.QRect(30, 210, 721, 251))
        self.Low_textEdit.setObjectName("Low_textEdit")
        self.Bottom_label = QtWidgets.QLabel(self.centralwidget)
        self.Bottom_label.setGeometry(QtCore.QRect(30, 490, 131, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Bottom_label.setFont(font)
        self.Bottom_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Bottom_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Bottom_label.setObjectName("Bottom_label")
        self.Bottom_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Bottom_pushButton.setGeometry(QtCore.QRect(660, 490, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bottom_pushButton.sizePolicy().hasHeightForWidth())
        self.Bottom_pushButton.setSizePolicy(sizePolicy)
        self.Bottom_pushButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Bottom_pushButton.setFont(font)
        self.Bottom_pushButton.setObjectName("Bottom_pushButton")
        self.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(self)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 22))
        # self.menubar.setObjectName("menubar")
        # self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.command()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        #self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Top_lineEdit.setPlaceholderText(_translate("MainWindow", "DR_template.txt"))
        self.Top_label.setText(_translate("MainWindow", "参考文档"))
        self.Top_pushButton.setText(_translate("MainWindow", "参考文档"))
        self.Mid_lineEdit.setPlaceholderText(_translate("MainWindow", "modbus.xls"))
        self.Mid_lable.setText(_translate("MainWindow", "数据列表"))
        self.Mid_pushButton.setText(_translate("MainWindow", "数据列表"))
        self.Low_label.setText(_translate("MainWindow", "结果"))
        self.Bottom_label.setText(_translate("MainWindow", "程序员美德"))
        self.Bottom_pushButton.setText(_translate("MainWindow", "确定"))

    def command(self):
        self.Top_pushButton.clicked.connect(lambda: self.openFileNameDialog('Top'))
        pass

    def openFileNameDialog(self,position):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        if position == "Top":
            fileName, _ = QFileDialog.getOpenFileName(self,"打开参考文档", "","All Files (*);;Template Files (*.txt)", options=options)
            if fileName:
                print(fileName)
                self.Top_lineEdit.setText(fileName)